// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hmulfwekqbryckdfzwkk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhtdWxmd2VrcWJyeWNrZGZ6d2trIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NjI5NTYsImV4cCI6MjA2MDEzODk1Nn0.hxkniVIZUhgcXIz9LDK-pdJGi1mSvPh-ZTNgE_Mzqkg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);